name: Waka Readme

on:
  schedule:
    - cron: '0 19 * * *' # 4:00 UTC+0900
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-20.04
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          # SHOW_COMMIT: "False"
          # SHOW_DAYS_OF_WEEK: "False"
          # SHOW_LANGUAGE: "False"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          # SHOW_TIMEZONE: "False"
          # SHOW_EDITORS: "False"
          # SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
      - run: |
          sed -i -e "s/░/ /g" README.md
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit --allow-empty -m "replace ░ with a space"
          git push origin master
